default: &default
  adapter: mysql2
  host: 127.0.0.1
  pool: 5
  timeout: 5000
  username: root
  password: imnPcNGDWWYB4q9CmaxLBCHn

development:
  <<: *default
  database: project-name-ruby-api_development

staging:
  <<: *default
  database: project-name-ruby-api_staging

test: &test
  <<: *default
  database: project-name-ruby-api_test

production:
  <<: *default
  database: project-name-ruby-api_production
  password: root
