default: &default
  adapter: mysql2
  host: 127.0.0.1
  pool: 5
  timeout: 5000
  username: mysql
  password: mysql

development:
  <<: *default
  database: wishlist-api_development

staging:
  <<: *default
  database: wishlist-api_staging

test: &test
  <<: *default
  database: wishlist-api_test

production:
  <<: *default
  database: wishlist-api_production
